name: generate-and-push
run-name: Fetched latest airtable data, run generate, push results
on:
  workflow_dispatch:
  
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: '3.10'
      - run: rm -f *.data.pickle
      - name: Run generate.py
        run: python generate.py
      #- name: Git commit
      #  run: git add games.json public/* && git commit -m 'updating'
