name: generate-and-push
run-name: Fetched latest airtable data, run generate, push results
on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: '3.10'
      - run: pip install requests
      - run: rm -f *.data.pickle
      - name: Run generate.py
        env:
          AIRTABLE_HOST: ${{ secrets.AIRTABLE_HOST }}
          AIRTABLE_KEY: ${{ secrets.AIRTABLE_KEY }}
          IGDB_CLIENTID: ${{ secrets.IGDB_CLIENTID }}
          IGDB_SECRET: ${{ secrets.IGDB_SECRET }}
        run: python generate.py
      - name: Git commit & push
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "abrochard@users.noreply.github.com"
          git add src/lib/games.json static/*
          git commit -m 'updating'
          git push
